### ISSUE TITLE
Bug: Yellow 3 pixel to left?

### ISSUE THREAD

**Issue by gitpower2017** [olanwe/img2vlw#1]
Hello.
With a small 70x70 icon, the yellow area is shifted approx. 3 pixels to the left.
A larger picture worked well.

![konverter_online](https://github.com/user-attachments/assets/fda11d76-3c0d-404e-b6ee-946f8f840412)
![display3pixel](https://github.com/user-attachments/assets/b937b125-b1e3-43fd-92c2-12fbef96c0cc)

**Comment by olanwe** [comment]
Hi!
That is strange. I just tried it with a similar bitmap (including a shifted color plane) and everything worked as expected (see below).
Could you please attach the PNG file if possible - or maybe point me to the source of the file?
The part of the JSON-file containing the image might be helpful too.
<img width="287" alt="Screenshot 2024-09-23 235913" src="https://github.com/user-attachments/assets/c6c520fb-4699-4c07-8f69-31ddc3956f3f">
<img width="287" alt="bitmap-test" src="https://github.com/user-attachments/assets/03345ec9-863b-4e2e-b50f-426dc5a42954">

**Comment by gitpower2017** [comment]
Hello.
Please find attached the jpg with the type 2 plug.

I use the whole thing with Node-Red. Here are two lines from the JS.
The first line works perfectly. The second line is the Typ2-plug.
`
...
const car = '{ "text": [0, 29, "0", "vwkfrontgelbschwarz.vlw", 1] }' + "," + '{ "text": [0, 29, "1", "vwkfrontgelbschwarz.vlw", 3] }';
...
var typ2 = '{ "text": [0, 100, "0", "ladesteker_smal.vlw", 1] }' + "," + '{ "text": [0, 100, "1", "ladesteker_smal.vlw", 3] }';//Gelb 
`
![charging_plugs_1-247370974](https://github.com/user-attachments/assets/b43d228e-7655-464a-b6f3-5f81552a2c0c)

**Comment by olanwe** [comment]
Thanks for your help! I was able to reproduce the behavior, but it seems to be either a rendering bug or a feature of the AP when placing the text at position 0, so this problem is not caused by the converter.

This is my sample JSON file:
```json
[  
  { "text": [0, 100, "0", "ladestecker_test.vlw", 1] },
  { "text": [0, 100, "1", "ladestecker_test.vlw", 3] },
  { "text": [1, 200, "0", "ladestecker_test.vlw", 1] },
  { "text": [1, 200, "1", "ladestecker_test.vlw", 3] } 
]
```
The first image is broken, just like yours. The second, however, renders as expected (and is shifted far more than a single pixel to the right):
<img width="287" alt="ei-ink_test" src="https://github.com/user-attachments/assets/7d048a8c-d97c-462e-94e9-24c21ab1357b">

Although this looks like a bug, it may actually be a feature. Perhaps the font renderer removes all unnecessary whitespace to ensure that the text starts at the very beginning of the display when the text position is set to 0.

**Comment by gitpower2017** [comment]
Thank you for your help with troubleshooting.
You are right. 
I have now created the plug with a small yellow spot on the left-hand side. Now it looks good even with a distance of 0.
Maybe post it on the website as a tip.
![typ2](https://github.com/user-attachments/assets/b281add7-7358-42b2-8d62-c36edf8965e1)

Danke

**Comment by gitpower2017** [comment]
Better Picture

![Typ2-Stecker](https://github.com/user-attachments/assets/71e87993-5056-409f-b5da-915293b67a8c)

**Comment by olanwe** [comment]
Hi @gitpower2017, I implemented a patch function ("x-pos 0 patch") that adds a pixel to the shifted color image so that both images (black and color) start at the same position. If you print the patched image first (in your case the yellow image), the added pixel will be invisible. Please try it and let me know if it works for you.
